version: "3"

services:
  dev-server:
    profiles:
      - dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"

  server:
    profiles:
      - prod
    build: .
    restart: unless-stopped
    env_file: .env

  https-portal:
    profiles:
      - prod
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    links:
      - server
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    environment:
      DOMAINS: >-
        ${DEPLOY_DOMAIN} -> http://server:3000
    env_file: .env

  # Redis にアカウント作成リクエストを保存する
  redis:
    image: redis/redis-stack:7.2.0-v4
    volumes:
      - "redis-data:/data"

volumes:
  redis-data: {}
