version: '3'

services:
  server:
    build: .
    restart: unless-stopped
    env_file: .env

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    links:
      - server
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    environment:
      DOMAINS: >-
        ${DEPLOY_DOMAIN} -> http://server:3000
    env_file: .env
