version: "3"

services:
  ## Development server ##

  dev-server:
    profiles:
      - dev
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
    networks:
      - ldap
      - redis

  ## Production servers ##

  server:
    profiles:
      - prod
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - prod
      - redis

  https-portal:
    profiles:
      - prod
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - prod
    volumes:
      - ./data/https-portal/certs:/var/lib/https-portal
    environment:
      # For production, change here to "production" once it works
      STAGE: staging
      DOMAINS: >-
        ${DEPLOY_DOMAIN} -> http://server:3000
    env_file: .env

  # Save account registration information in Redis
  redis:
    profiles:
      - dev
      - prod
    image: redis/redis-stack:7.2.0-v4
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "./data/redis:/data"
    networks:
      - redis
    env_file: .env

  ## LDAP servers for local development ##

  slapd: # OpenLDAPサーバ
    profiles:
      - ldap
    image: osixia/openldap:1.5.0
    container_name: slapd
    restart: on-failure:3
    hostname: ldap.jn.sfc.keio.ac.jp
    ports:
      - 127.0.0.1:8636:636
      - 127.0.0.1:8389:389
    environment:
      LDAP_ORGANISATION: "Jn lab"
      LDAP_DOMAIN: "jn.sfc.keio.ac.jp"
      LDAP_BASE_DN: "dc=jn,dc=sfc,dc=keio,dc=ac,dc=jp"
      LDAP_TLS: "false"
      LDAP_TLS_ENFORCE: "false"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
    env_file:
      - .ldap.env
    volumes:
      - ./data/ldap_db:/var/lib/ldap
      - ./data/ldap_config:/etc/ldap/slapd.d
      - ./data/https-portal/ldap.jn.sfc.keio.ac.jp/production:/container/service/slapd/assets/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldap

  # Ldap Account Manager (LAM) server, for manage local LDAP server
  lam:
    profiles:
      - ldap
    build:
      dockerfile: ./lam.dockerfile
      context: .
    container_name: lam
    restart: on-failure:3
    environment:
      LDAP_DOMAIN: "jn.sfc.keio.ac.jp"
      LDAP_BASE_DN: "dc=jn,dc=sfc,dc=keio,dc=ac,dc=jp"
      LDAP_USERS_DN: "ou=people,dc=jn,dc=sfc,dc=keio,dc=ac,dc=jp"
      LDAP_GROUPS_DN: "ou=groups,dc=jn,dc=sfc,dc=keio,dc=ac,dc=jp"
      LDAP_SERVER: "ldap://slapd"
      LDAP_ORGANISATION: "Jn lab"
      LAM_LANG: "ja_JP"
      # LAM_PASSWORD: "lam"
    env_file:
      - .env
    depends_on:
      - slapd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - ldap
    ports:
      - "8081:80"

networks:
  prod: {}
  ldap: {}
  redis: {}
